# Production-specific configuration
version: '3.8'

services:
  backend:
    restart: always
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
    volumes:
      - ./backend/uploads:/app/uploads
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: []
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: legalai-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

  postgres:
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

  redis:
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

secrets:
  db_password:
    file: ./secrets/db_password.txt