# Development-specific overrides
version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - DEBUG=true
      - RELOAD=true
      - DISABLE_AUTH=false  # Should be false for auth testing
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  # Development tools
  mailhog:
    image: mailhog/mailhog:latest
    container_name: legalai-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    profiles:
      - tools